export const FETCH_SHOWS = 'TVSHOWS/FETCH_SHOWS';
export const SHOW_LOADER = 'TVSHOWS/SHOW_LOADER';
export const HIDE_LOADER = 'TVSHOWS/HIDE_LOADER';
export const SHOW_LIST_IS_EMPTY = 'TVSHOWS/NO_SHOWS';
export const FETCH_SHOW_BY_ID = 'TVSHOWS/FETCH_SHOW_BY_ID';
export const FETCH_SHOW_ERROR = 'TVSHOWS/FETCH_SHOW_ERROR';
export const FETCH_ERROR_CLEAR = 'TVSHOWS/FETCH_ERROR_CLEAR';